import { DeviceDriver } from '../driver-types';

export const Device: DeviceDriver = {
  name: 'MixTrack Pro FX',
  type: 'normal',
  anonymous: false,
  height: 9.5,
  width: 21.2,
  style: {},
  controlSequence: [
    [240, 0, 32, 127, 3, 1, 247],
    [240, 126, 0, 6, 1, 247],
    [240, 0, 32, 127, 19, 247],
  ],
  inputGrids: [
    {
      id: 'MasterKnob',
      height: 0.5,
      width: 0.5,
      left: 20.2,
      bottom: 8.375,
      nRows: 1,
      nCols: 1,
      inputs: [
        {
          interactive: true,
          status: 'controlchange',
          number: 35,
          channel: 14,
          response: 'continuous',
          type: 'knob',
          width: 0.5,
          height: 0.5,
          shape: 'circle',
          knobType: 'absolute',
          style: {},
          availableColors: [],
          availableFx: [],
        },
      ],
    },
    {
      id: 'MicKnob',
      height: 0.5,
      width: 0.5,
      left: 0.5,
      bottom: 8.375,
      nRows: 1,
      nCols: 1,
      inputs: [
        {
          interactive: false,
          width: 0.5,
          height: 0.5,
          type: 'knob',
          shape: 'circle',
          style: {},
        },
      ],
    },
    {
      id: 'Big Turny Boi Left',
      height: 6,
      width: 6,
      left: 0.625,
      bottom: 2.625,
      nRows: 1,
      nCols: 1,
      inputs: [
        {
          interactive: true,
          status: 'controlchange',
          number: 6,
          channel: 0,
          response: 'continuous',
          type: 'knob',
          width: 6,
          height: 6,
          shape: 'circle',
          knobType: 'endless',
          style: {},
          availableColors: [],
          availableFx: [],
        },
      ],
    },
    {
      id: 'Big Turny Boi Right',
      height: 6,
      width: 6,
      left: 13.6,
      bottom: 2.625,
      nRows: 1,
      nCols: 1,
      inputs: [
        {
          interactive: true,
          status: 'controlchange',
          number: 6,
          channel: 1,
          response: 'continuous',
          type: 'knob',
          width: 6,
          height: 6,
          shape: 'circle',
          knobType: 'endless',
          style: {},
          availableColors: [],
          availableFx: [],
        },
      ],
    },
    {
      id: 'Big Slider Left',
      height: 4.625,
      width: 0.75,
      left: 7,
      bottom: 3.125,
      nRows: 1,
      nCols: 1,
      inputs: [
        {
          interactive: true,
          status: 'controlchange',
          number: 9,
          channel: 0,
          response: 'continuous',
          type: 'slider',
          width: 0.75,
          height: 4.625,
          shape: 'rect',
          handleWidth: 0.75,
          handleHeight: 0.5,
          style: {
            transform: 'rotate(180deg)',
          },
          availableColors: [],
          availableFx: [],
        },
      ],
    },
    {
      id: 'Big Slider Right',
      height: 4.625,
      width: 0.75,
      left: 20.1,
      bottom: 3.125,
      nRows: 1,
      nCols: 1,
      inputs: [
        {
          interactive: true,
          status: 'controlchange',
          number: 9,
          channel: 1,
          response: 'continuous',
          type: 'slider',
          width: 0.75,
          height: 4.625,
          shape: 'rect',
          handleWidth: 0.75,
          handleHeight: 0.5,
          style: {
            transform: 'rotate(180deg)',
          },
          availableColors: [],
          availableFx: [],
        },
      ],
    },
  ],
};
