import { Color } from '../driver-types/color';
import { DeviceDriver } from '../driver-types/device-driver';
import { KnobDriver } from '../driver-types/input-drivers/knob-driver';
import { PadDriver } from '../driver-types/input-drivers/pad-driver';

function mainPadColors(n: MidiNumber): Color[] {
  return [
    {
      default: true,
      name: 'Off',
      string: 'transparent',
      array: [144, n, 0],
      effectable: false,
    },
    {
      name: 'Green',
      string: '#4CAF50',
      array: [144, n, 1],
      effectable: false,
    },
    {
      modifier: 'blink',
      name: 'Green',
      string: '#4CAF50',
      array: [144, n, 2],
      effectable: false,
    },
    {
      name: 'Red',
      string: '#F44336',
      array: [144, n, 3],
      effectable: false,
    },
    {
      modifier: 'blink',
      name: 'Red',
      string: '#F44336',
      array: [144, n, 4],
      effectable: false,
    },
    {
      name: 'Yellow',
      string: '#FFC107',
      array: [144, n, 5],
      effectable: false,
    },
    {
      modifier: 'blink',
      name: 'Yellow',
      string: '#FFC107',
      array: [144, n, 6],
      effectable: false,
    },
  ];
}

function createMainPad(n: MidiNumber): PadDriver {
  return {
    interactive: true,
    status: 'noteon/noteoff',
    channel: 0,
    number: n,
    response: 'gate',
    type: 'pad',
    width: 0.5,
    height: 0.3,
    shape: 'rect',
    availableColors: mainPadColors(n),
    availableFx: [],
  };
}

function createSquareColors(n: MidiNumber): Color[] {
  return [
    {
      default: true,
      name: 'Off',
      string: 'transparent',
      array: [144, n, 0],
      effectable: false,
    },
    {
      name: 'Red',
      string: '#F44336',
      array: [144, n, 1],
      effectable: false,
    },
    {
      name: 'Red',
      string: '#F44336',
      modifier: 'blink',
      array: [144, n, 2],
      effectable: false,
    },
  ];
}

function createHoriCirclePad(n: MidiNumber): PadDriver {
  return {
    interactive: true,
    status: 'noteon/noteoff',
    channel: 0,
    number: n,
    response: 'gate',
    shape: 'circle',
    type: 'pad',
    width: 0.25,
    height: 0.25,
    availableColors: createSquareColors(n),
    availableFx: [],
  };
}

function createVertCircleColors(n: MidiNumber): Color[] {
  return [
    {
      default: true,
      name: 'Off',
      string: 'transparent',
      array: [144, n, 0],
      effectable: false,
    },
    {
      name: 'Green',
      string: '#4CAF50',
      array: [144, n, 1],
      effectable: false,
    },
    {
      modifier: 'blink',
      name: 'Green',
      string: '#4CAF50',
      array: [144, n, 2],
      effectable: false,
    },
  ];
}

function createVertPad(n: MidiNumber): PadDriver {
  return {
    interactive: true,
    status: 'noteon/noteoff',
    channel: 0,
    number: n,
    response: 'gate',
    shape: 'circle',
    type: 'pad',
    width: 0.25,
    height: 0.25,
    availableColors: createVertCircleColors(n),
    availableFx: [],
  };
}

function createKnob(n: MidiNumber): KnobDriver {
  return {
    interactive: true,
    status: 'controlchange',
    number: n,
    channel: 0,
    response: 'continuous',
    type: 'knob',
    width: 0.5,
    height: 0.5,
    shape: 'circle',
    knobType: 'absolute',
    availableColors: [],
    availableFx: [],
  };
}

export const Device: DeviceDriver = {
  name: 'APC Key 25',
  type: 'normal',
  anonymous: false,
  height: 7.5,
  width: 12.125,
  controlSequence: [],
  style: {
    borderTopLeftRadius: '2em',
    borderTopRightRadius: '2em',
    borderBottomLeftRadius: '1em',
    borderBottomRightRadius: '1em',
  },
  keyboard: {
    defaultOctave: 2,
    nOctaves: 2,
    channel: 1,
    width: 11.5,
    height: 3.125,
    left: 0.3125,
    bottom: 0,
    enabled: true,
  },
  inputGrids: [
    {
      id: 'MainPads',
      height: 3.75,
      width: 6.375,
      left: 0.375,
      bottom: 3.5,
      nRows: 6,
      nCols: 8,
      inputs: [
        createMainPad(32),
        createMainPad(33),
        createMainPad(34),
        createMainPad(35),
        createMainPad(36),
        createMainPad(37),
        createMainPad(38),
        createMainPad(39),
        createMainPad(24),
        createMainPad(25),
        createMainPad(26),
        createMainPad(27),
        createMainPad(28),
        createMainPad(29),
        createMainPad(30),
        createMainPad(31),
        createMainPad(16),
        createMainPad(17),
        createMainPad(18),
        createMainPad(19),
        createMainPad(20),
        createMainPad(21),
        createMainPad(22),
        createMainPad(23),
        createMainPad(8),
        createMainPad(9),
        createMainPad(10),
        createMainPad(11),
        createMainPad(12),
        createMainPad(13),
        createMainPad(14),
        createMainPad(15),
        createMainPad(0),
        createMainPad(1),
        createMainPad(2),
        createMainPad(3),
        createMainPad(4),
        createMainPad(5),
        createMainPad(6),
        createMainPad(7),
        createHoriCirclePad(64),
        createHoriCirclePad(65),
        createHoriCirclePad(66),
        createHoriCirclePad(67),
        createHoriCirclePad(68),
        createHoriCirclePad(69),
        createHoriCirclePad(70),
        createHoriCirclePad(71),
      ],
    },
    {
      id: 'VertCircles',
      height: 3.75,
      width: 0.5,
      left: 6.85,
      bottom: 3.5,
      nRows: 6,
      nCols: 1,
      inputs: [
        createVertPad(82),
        createVertPad(83),
        createVertPad(84),
        createVertPad(85),
        createVertPad(86),
        {
          interactive: true,
          status: 'noteon/noteoff',
          channel: 0,
          number: 81,
          response: 'gate',
          shape: 'circle',
          type: 'pad',
          width: 0.25,
          height: 0.25,
          availableColors: [],
          availableFx: [],
        },
      ],
    },
    {
      id: 'Knobs',
      height: 2.25,
      width: 4.25,
      bottom: 5,
      left: 7.45,
      nRows: 2,
      nCols: 4,
      inputs: [
        createKnob(48),
        createKnob(49),
        createKnob(50),
        createKnob(51),
        createKnob(52),
        createKnob(53),
        createKnob(54),
        createKnob(55),
      ],
    },
    {
      id: 'Aux1',
      height: 1.25,
      width: 4,
      left: 7.625,
      bottom: 3.5,
      nRows: 2,
      nCols: 5,
      inputs: [
        {
          interactive: true,
          status: 'controlchange',
          channel: 1,
          number: 64,
          response: 'gate',
          shape: 'rect',
          type: 'pad',
          width: 0.5,
          height: 0.25,
          availableColors: [],
          availableFx: [],
        },
        {
          interactive: false,
          width: 0.5,
          height: 0.25,
          type: 'pad',
          shape: 'rect',
        },
        {
          interactive: false,
          width: 0.5,
          height: 0.25,
          type: 'pad',
          shape: 'rect',
        },
        {
          interactive: true,
          status: 'controlchange',
          channel: 0,
          number: 91,
          response: 'gate',
          shape: 'rect',
          type: 'pad',
          width: 0.5,
          height: 0.25,
          availableColors: [],
          availableFx: [],
        },
        {
          interactive: true,
          status: 'controlchange',
          channel: 0,
          number: 93,
          response: 'gate',
          shape: 'rect',
          type: 'pad',
          width: 0.5,
          height: 0.25,
          availableColors: [],
          availableFx: [],
        },
        {
          interactive: true,
          status: 'noteon/noteoff',
          channel: 0,
          number: 98,
          response: 'gate',
          shape: 'rect',
          type: 'pad',
          width: 0.5,
          height: 0.25,
          availableColors: [],
          availableFx: [],
        },
      ],
    },
  ],
};
