import { KnobDriver } from '../driver-types/input-drivers/knob-driver';
import { PadDriver } from '../driver-types/input-drivers/pad-driver';
import { DeviceDriver } from '../driver-types/device-driver';
import { NoninteractiveInputDriver } from '../driver-types/input-drivers';

function createSquarePad(n: MidiNumber): PadDriver {
  return {
    interactive: true,
    status: 'noteon/noteoff',
    channel: 0,
    number: n,
    response: 'gate',
    shape: 'rect',
    type: 'pad',
    width: 1,
    height: 1,
    availableColors: [],
    availableFx: [],
  };
}

function createTransport(n: MidiNumber): PadDriver {
  return {
    interactive: true,
    status: 'controlchange',
    channel: 0,
    number: n,
    value: 127,
    response: 'constant',
    shape: 'rect',
    type: 'pad',
    width: 0.4,
    height: 0.25,
    availableColors: [],
    availableFx: [],
  };
}

function createKnob(n: MidiNumber): KnobDriver {
  return {
    interactive: true,
    status: 'controlchange',
    number: n,
    channel: 0,
    response: 'continuous',
    type: 'knob',
    width: 0.5,
    height: 0.5,
    shape: 'circle',
    knobType: 'absolute',
    availableColors: [],
    availableFx: [],
  };
}

function createNoninteractivePad(
  width: number,
  height: number
): NoninteractiveInputDriver {
  return {
    interactive: false,
    width,
    height,
    type: 'pad',
    shape: 'rect',
  };
}

export const Device: DeviceDriver = {
  name: 'MPK mini Plus Port 1',
  type: 'normal',
  anonymous: false,
  height: 7,
  width: 17.75,
  controlSequence: [],
  style: {},
  keyboard: {
    defaultOctave: 2,
    nOctaves: 3,
    channel: 0,
    width: 17,
    height: 3.25,
    left: 0.325,
    bottom: 0,
    enabled: true,
  },
  inputGrids: [
    {
      id: 'Wheels',
      height: 1.625,
      width: 3.25,
      left: 0,
      bottom: 4.125,
      nRows: 1,
      nCols: 2,
      inputs: [
        {
          status: 'pitchbend',
          channel: 0,
          number: 0,
          type: 'wheel',
          width: 0.5,
          height: 1.625,
          shape: 'rect',
          interactive: true,
          response: 'continuous',
          handleWidth: 0.5,
          handleHeight: 0.5,
          horizontal: false,
          inverted: false,
          availableColors: [],
          availableFx: [],
        },
        {
          status: 'controlchange',
          channel: 0,
          number: 1,
          type: 'wheel',
          width: 0.5,
          height: 1.625,
          shape: 'rect',
          interactive: true,
          response: 'continuous',
          handleWidth: 0.5,
          handleHeight: 0.5,
          horizontal: false,
          inverted: false,
          availableColors: [],
          availableFx: [],
        },
      ],
    },
    {
      id: 'XY',
      height: 0.9,
      width: 0.9,
      left: 3.125,
      bottom: 5.75,
      nRows: 1,
      nCols: 1,
      inputs: [
        {
          type: 'xy',
          interactive: true,
          shape: 'circle',
          height: 0.9,
          width: 0.9,
          xPolarity: 'unipolar',
          yPolarity: 'bipolar',
          x: {
            status: 'controlchange',
            channel: 0,
            number: 12,
            type: 'slider',
            width: 0.9,
            height: 0.9,
            shape: 'circle',
            interactive: true,
            response: 'continuous',
            handleWidth: 0.5,
            handleHeight: 0.5,
            horizontal: false,
            inverted: false,
            availableColors: [],
            availableFx: [],
          },
          y: {
            status: 'controlchange',
            channel: 0,
            number: 2,
            type: 'slider',
            width: 0.9,
            height: 0.9,
            shape: 'circle',
            interactive: true,
            response: 'continuous',
            handleWidth: 0.5,
            handleHeight: 0.5,
            horizontal: false,
            inverted: false,
            availableColors: [],
            availableFx: [],
          },
        },
      ],
    },
    {
      id: 'Arpeggiator',
      height: 1.25,
      width: 1.25,
      left: 3,
      bottom: 4,
      nRows: 3,
      nCols: 2,
      inputs: [
        createNoninteractivePad(0.45, 0.25),
        createNoninteractivePad(0.45, 0.25),
        createNoninteractivePad(0.45, 0.25),
        createNoninteractivePad(0.45, 0.25),
        createNoninteractivePad(0.45, 0.25),
        createNoninteractivePad(0.45, 0.25),
      ],
    },
    {
      id: 'Pads',
      height: 2.5,
      width: 5.125,
      bottom: 4,
      left: 4.5,
      nRows: 2,
      nCols: 4,
      inputs: [
        createSquarePad(40),
        createSquarePad(41),
        createSquarePad(42),
        createSquarePad(43),
        createSquarePad(36),
        createSquarePad(37),
        createSquarePad(38),
        createSquarePad(39),
      ],
    },
    {
      id: 'Knobs',
      height: 2.125,
      width: 4.25,
      bottom: 4.625,
      left: 13.125,
      nRows: 2,
      nCols: 4,
      inputs: [
        createKnob(70),
        createKnob(71),
        createKnob(72),
        createKnob(73),
        createKnob(74),
        createKnob(75),
        createKnob(76),
        createKnob(77),
      ],
    },
    {
      id: 'Transport',
      height: 0.375,
      width: 4,
      left: 13.4,
      bottom: 4,
      nRows: 1,
      nCols: 6,
      inputs: [
        createTransport(115),
        createTransport(116),
        createTransport(117),
        createTransport(118),
        createTransport(119),
        createNoninteractivePad(0.4, 0.25),
      ],
    },
    {
      id: 'Screen',
      height: 0.625,
      width: 1.375,
      left: 10.25,
      bottom: 5.75,
      nRows: 1,
      nCols: 1,
      inputs: [createNoninteractivePad(1.375, 0.625)],
    },
    {
      id: 'ControlKnob',
      height: 0.6,
      width: 0.6,
      left: 12.125,
      bottom: 5.85,
      nRows: 1,
      nCols: 1,
      inputs: [
        {
          interactive: false,
          width: 0.6,
          height: 0.6,
          type: 'knob',
          shape: 'circle',
        },
      ],
    },
    {
      id: 'Misc Buttons',
      height: 1.25,
      width: 2.5,
      left: 10.2,
      bottom: 4,
      nRows: 2,
      nCols: 3,
      inputs: [
        createNoninteractivePad(0.45, 0.25),
        createNoninteractivePad(0.45, 0.25),
        createNoninteractivePad(0.45, 0.25),
        createNoninteractivePad(0.45, 0.25),
        createNoninteractivePad(0.45, 0.25),
        createNoninteractivePad(0.45, 0.25),
      ],
    },
  ],
};
