import { DeviceDriver, Color } from '../driver-types';
import { PadDriver, KnobDriver } from '../driver-types/input-drivers';

function mainPadColors(n: MidiNumber): Color[] {
  return [
    {
      default: true,
      name: 'Off',
      string: 'transparent',
      array: [144, n, 0],
      effectable: false,
    },
    {
      name: 'Red',
      string: '#F44336',
      array: [144, n, 5],
      effectable: true,
    },
    {
      name: 'Orange',
      string: '#F57C00',
      array: [144, n, 60],
      effectable: true,
    },
    {
      name: 'Yellow',
      string: '#FFEB3B',
      array: [144, n, 9],
      effectable: true,
    },
    {
      name: 'Seafoam Green',
      string: '#E0F7FA',
      array: [144, n, 8],
      effectable: true,
    },
    {
      name: 'Soft Green',
      string: '#C8E6C9',
      array: [144, n, 12],
      effectable: true,
    },
    {
      name: 'Pea Green',
      string: '#9CCC65',
      array: [144, n, 13],
      effectable: true,
    },
    {
      name: 'Green',
      string: '#4CAF50',
      array: [144, n, 21],
      effectable: true,
    },
    {
      name: 'Teal-ish',
      string: '#4DB6AC',
      array: [144, n, 20],
      effectable: true,
    },
    {
      name: 'Light Blue',
      string: '#64B5F6',
      array: [144, n, 32],
      effectable: true,
    },
    {
      name: 'Blue',
      string: '#2196F3',
      array: [144, n, 41],
      effectable: true,
    },
    {
      name: 'Royal Blue',
      string: '#163bc4',
      array: [144, n, 45],
      effectable: true,
    },
    {
      name: 'Fuchsia',
      string: '#BA68C8',
      array: [144, n, 53],
      effectable: true,
    },
    {
      name: 'Pink',
      string: '#F06292',
      array: [144, n, 57],
      effectable: true,
    },
    {
      name: 'Translucent Purple',
      string: '#E1BEE7',
      array: [144, n, 56],
      effectable: true,
    },
    {
      name: 'Pepper White',
      string: '#E8EAF6',
      array: [144, n, 107],
      effectable: true,
    },
  ];
}

function squarePadColors(n: MidiNumber): Color[] {
  return [
    {
      name: 'Off',
      default: true,
      string: 'transparent',
      array: [144, n, 0],
      effectable: false,
    },
    {
      name: 'Red',
      string: '#F44336',
      array: [144, n, 1],
      effectable: false,
    },
    {
      name: 'Red',
      string: '#F44336',
      array: [144, n, 2],
      modifier: 'blink',
      effectable: false,
    },
  ];
}

function circlePadColors(n: MidiNumber): Color[] {
  return [
    {
      default: true,
      name: 'Off',
      string: 'transparent',
      array: [144, n, 0],
      effectable: false,
    },
    {
      name: 'Green',
      string: '#4CAF50',
      array: [144, n, 1],
      effectable: false,
    },
    {
      modifier: 'blink',
      name: 'Green',
      string: '#4CAF50',
      array: [144, n, 2],
      effectable: false,
    },
  ];
}

function createMainPad(n: MidiNumber): PadDriver {
  return {
    interactive: true,
    status: 'noteon/noteoff',
    channel: 0,
    number: n,
    response: 'gate',
    type: 'pad',
    width: 0.5,
    height: 0.3,
    shape: 'rect',
    availableColors: mainPadColors(n),
    availableFx: [
      {
        title: 'Solid',
        effect: 'Brightness',
        isDefault: true,
        validVals: [
          [1, 0, 0],
          [2, 0, 0],
          [3, 0, 0],
          [4, 0, 0],
          [5, 0, 0],
          [6, 0, 0],
        ],
        defaultVal: [6, 0, 0],
        lowBoundLabel: 'Dim',
        highBoundLabel: 'Bright',
      },
      {
        title: 'Pulse',
        effect: 'Speed',
        isDefault: false,
        validVals: [
          [7, 0, 0],
          [8, 0, 0],
          [9, 0, 0],
          [10, 0, 0],
        ],
        defaultVal: [7, 0, 0],
        lowBoundLabel: 'Fast',
        highBoundLabel: 'Slow',
      },
      {
        title: 'Blink',
        effect: 'Speed',
        isDefault: false,
        validVals: [
          [11, 0, 0],
          [12, 0, 0],
          [13, 0, 0],
          [14, 0, 0],
          [15, 0, 0],
        ],
        defaultVal: [11, 0, 0],
        lowBoundLabel: 'Fast',
        highBoundLabel: 'Slow',
      },
    ],
  };
}

function createSquarePad(n: MidiNumber): PadDriver {
  return {
    interactive: true,
    status: 'noteon/noteoff',
    channel: 0,
    number: n,
    response: 'gate',
    shape: 'rect',
    type: 'pad',
    width: 0.25,
    height: 0.25,
    availableColors: squarePadColors(n),
    availableFx: [],
  };
}

function createVertPad(n: MidiNumber): PadDriver {
  return {
    interactive: true,
    status: 'noteon/noteoff',
    channel: 0,
    number: n,
    response: 'gate',
    shape: 'rect',
    type: 'pad',
    width: 0.25,
    height: 0.25,
    availableColors: circlePadColors(n),
    availableFx: [],
  };
}

function createKnob(n: MidiNumber): KnobDriver {
  return {
    interactive: true,
    status: 'controlchange',
    number: n,
    channel: 0,
    response: 'continuous',
    type: 'knob',
    width: 0.5,
    height: 0.5,
    shape: 'circle',
    knobType: 'endless',
    availableColors: [],
    availableFx: [],
  };
}

export const Device: DeviceDriver = {
  name: 'APC Key 25 mk2 Control',
  type: 'normal',
  anonymous: false,
  height: 7.5,
  width: 12.125,
  controlSequence: [],
  style: {},
  keyboard: {
    defaultOctave: 2,
    nOctaves: 2,
    channel: 0,
    width: 11.5,
    height: 3.125,
    left: 0.3125,
    bottom: 0,
    enabled: false,
  },
  inputGrids: [
    {
      id: 'MainPads',
      height: 3.75,
      width: 6.375,
      left: 0.375,
      bottom: 3.5,
      nRows: 6,
      nCols: 8,
      inputs: [
        createMainPad(32),
        createMainPad(33),
        createMainPad(34),
        createMainPad(35),
        createMainPad(36),
        createMainPad(37),
        createMainPad(38),
        createMainPad(39),
        createMainPad(24),
        createMainPad(25),
        createMainPad(26),
        createMainPad(27),
        createMainPad(28),
        createMainPad(29),
        createMainPad(30),
        createMainPad(31),
        createMainPad(16),
        createMainPad(17),
        createMainPad(18),
        createMainPad(19),
        createMainPad(20),
        createMainPad(21),
        createMainPad(22),
        createMainPad(23),
        createMainPad(8),
        createMainPad(9),
        createMainPad(10),
        createMainPad(11),
        createMainPad(12),
        createMainPad(13),
        createMainPad(14),
        createMainPad(15),
        createMainPad(0),
        createMainPad(1),
        createMainPad(2),
        createMainPad(3),
        createMainPad(4),
        createMainPad(5),
        createMainPad(6),
        createMainPad(7),
        createSquarePad(64),
        createSquarePad(65),
        createSquarePad(66),
        createSquarePad(67),
        createSquarePad(68),
        createSquarePad(69),
        createSquarePad(70),
        createSquarePad(71),
      ],
    },
    {
      id: 'VertCircles',
      height: 3.75,
      width: 0.5,
      left: 6.85,
      bottom: 3.5,
      nRows: 6,
      nCols: 1,
      inputs: [
        createVertPad(82),
        createVertPad(83),
        createVertPad(84),
        createVertPad(85),
        createVertPad(86),
        {
          interactive: true,
          status: 'noteon/noteoff',
          channel: 0,
          number: 81,
          response: 'gate',
          shape: 'rect',
          type: 'pad',
          width: 0.25,
          height: 0.25,
          availableColors: [],
          availableFx: [],
        },
      ],
    },
    {
      id: 'Knobs',
      height: 2.25,
      width: 4.25,
      bottom: 5,
      left: 7.45,
      nRows: 2,
      nCols: 4,
      inputs: [
        createKnob(48),
        createKnob(49),
        createKnob(50),
        createKnob(51),
        createKnob(52),
        createKnob(53),
        createKnob(54),
        createKnob(55),
      ],
    },
    {
      id: 'Aux1',
      height: 1.25,
      width: 4,
      left: 7.625,
      bottom: 3.5,
      nRows: 2,
      nCols: 5,
      inputs: [
        {
          interactive: false,
          width: 0.5,
          height: 0.3,
          type: 'pad',
          shape: 'rect',
        },
        {
          interactive: false,
          width: 0.5,
          height: 0.3,
          type: 'pad',
          shape: 'rect',
        },
        {
          interactive: false,
          width: 0.5,
          height: 0.3,
          type: 'pad',
          shape: 'rect',
        },
        {
          interactive: true,
          status: 'noteon/noteoff',
          channel: 0,
          number: 91,
          response: 'gate',
          shape: 'rect',
          type: 'pad',
          width: 0.5,
          height: 0.3,
          availableColors: [],
          availableFx: [],
        },
        {
          interactive: true,
          status: 'noteon/noteoff',
          channel: 0,
          number: 93,
          response: 'gate',
          shape: 'rect',
          type: 'pad',
          width: 0.5,
          height: 0.3,
          availableColors: [],
          availableFx: [],
        },
        {
          interactive: true,
          status: 'noteon/noteoff',
          channel: 0,
          number: 98,
          response: 'gate',
          shape: 'rect',
          type: 'pad',
          width: 0.5,
          height: 0.3,
          availableColors: [],
          availableFx: [],
        },
      ],
    },
  ],
};
