import { KnobDriver } from '../driver-types/input-drivers/knob-driver';
import { PadDriver } from '../driver-types/input-drivers/pad-driver';
import { DeviceDriver } from '../driver-types/device-driver';
import { NoninteractiveInputDriver } from '../driver-types/input-drivers';

function createNoninteractivePad(
  width: number,
  height: number,
): NoninteractiveInputDriver {
  return {
    interactive: false,
    width,
    height,
    type: 'pad',
    shape: 'rect',
  };
}

function createNoninteractiveKnob(
  width: number,
  height: number,
): NoninteractiveInputDriver {
  return {
    interactive: false,
    width,
    height,
    type: 'knob',
    shape: 'circle',
  };
}

function createTransport(n: MidiNumber): PadDriver {
  return {
    interactive: true,
    status: 'controlchange',
    channel: 0,
    number: n,
    type: 'pad',
    width: 0.6,
    height: 0.5,
    shape: 'rect',
    response: 'gate',
    availableColors: [],
    availableFx: [],
  };
}

function createPad(n: MidiNumber): PadDriver {
  return {
    interactive: true,
    status: 'noteon/noteoff',
    channel: 0,
    number: n,
    type: 'pad',
    width: 1,
    height: 1,
    shape: 'rect',
    response: 'gate',
    availableColors: [],
    availableFx: [],
  };
}

function createKnob(n: MidiNumber): KnobDriver {
  return {
    interactive: true,
    status: 'controlchange',
    number: n,
    channel: 0,
    response: 'continuous',
    type: 'knob',
    width: 0.75,
    height: 0.75,
    shape: 'circle',
    knobType: 'absolute',
    availableColors: [],
    availableFx: [],
  };
}

export const Device: DeviceDriver = {
  name: 'Impulse',
  type: 'normal',
  anonymous: false,
  width: 20,
  height: 11.75,
  controlSequence: [],
  style: {
    borderTopLeftRadius: '0.5em',
    borderTopRightRadius: '0.5em',
    borderBottomLeftRadius: '0.5em',
    borderBottomRightRadius: '0.5em',
  },
  keyboard: {
    defaultOctave: 2,
    nOctaves: 2,
    channel: 0,
    width: 14.75,
    height: 5.625,
    left: 3.875,
    bottom: 0,
    enabled: true,
  },
  inputGrids: [
    {
      id: 'Wheels',
      height: 1.875,
      width: 2.125,
      left: 1,
      bottom: 2.375,
      nRows: 1,
      nCols: 2,
      inputs: [
        {
          interactive: true,
          status: 'pitchbend',
          channel: 0,
          number: 0,
          type: 'wheel',
          width: 0.55,
          height: 1.875,
          shape: 'rect',
          response: 'continuous',
          handleWidth: 0.55,
          handleHeight: 0.25,
          horizontal: false,
          inverted: false,
          availableColors: [],
          availableFx: [],
        },
        {
          interactive: true,
          status: 'controlchange',
          channel: 0,
          number: 1,
          type: 'wheel',
          width: 0.55,
          height: 1.875,
          shape: 'rect',
          response: 'continuous',
          handleWidth: 0.55,
          handleHeight: 0.25,
          horizontal: false,
          inverted: false,
          availableColors: [],
          availableFx: [],
        },
      ],
    },
    {
      id: 'Screen',
      height: 2,
      width: 3.625,
      left: 2.6,
      bottom: 8.5,
      nRows: 1,
      nCols: 1,
      inputs: [createNoninteractivePad(3.625, 2)],
    },
    {
      id: 'Transpose',
      height: 0.4,
      width: 1.125,
      left: 1.5,
      bottom: 5,
      nRows: 1,
      nCols: 2,
      inputs: [
        createNoninteractivePad(0.4, 0.4),
        createNoninteractivePad(0.4, 0.4),
      ],
    },
    {
      id: 'Fader',
      height: 3,
      width: 0.7,
      left: 1,
      bottom: 7.35,
      nRows: 1,
      nCols: 1,
      inputs: [
        {
          interactive: true,
          status: 'controlchange',
          number: 49,
          channel: 0,
          response: 'continuous',
          type: 'slider',
          width: 0.7,
          height: 2.875,
          shape: 'rect',
          handleWidth: 0.7,
          handleHeight: 0.625,
          horizontal: false,
          inverted: false,
          availableColors: [],
          availableFx: [],
        },
      ],
    },
    {
      id: 'MixerButton',
      height: 0.4,
      width: 0.5,
      left: 1.375,
      bottom: 6,
      nRows: 1,
      nCols: 1,
      inputs: [createNoninteractivePad(0.5, 0.4)],
    },
    {
      id: 'Template Edit',
      height: 1.5,
      width: 5.6,
      left: 2.375,
      bottom: 6.25,
      nRows: 2,
      nCols: 4,
      inputs: [
        createNoninteractivePad(0.75, 0.5),
        createNoninteractivePad(0.75, 0.5),
        createNoninteractivePad(0.75, 0.5),
        createNoninteractivePad(0.75, 0.5),
        createNoninteractivePad(0.75, 0.5),
        createNoninteractivePad(0.75, 0.5),
        createNoninteractivePad(0.75, 0.5),
        createNoninteractivePad(0.75, 0.5),
      ],
    },
    {
      id: 'Clip Launch',
      height: 0.5,
      width: 2.125,
      left: 15.6,
      bottom: 6.75,
      nRows: 1,
      nCols: 2,
      inputs: [
        createNoninteractivePad(0.75, 0.5),
        createNoninteractivePad(0.75, 0.5),
      ],
    },
    {
      id: 'Page',
      height: 1,
      width: 0.4,
      left: 8.25,
      bottom: 9,
      nRows: 2,
      nCols: 1,
      inputs: [
        createNoninteractivePad(0.4, 0.4),
        createNoninteractivePad(0.4, 0.4),
      ],
    },
    {
      id: 'DataKnob',
      height: 0.875,
      width: 0.875,
      left: 6.75,
      bottom: 9.125,
      nRows: 1,
      nCols: 1,
      inputs: [createNoninteractiveKnob(0.875, 0.875)],
    },
    {
      id: 'TransportCtrls',
      height: 0.4,
      width: 5,
      left: 8.5,
      bottom: 6.4,
      nRows: 1,
      nCols: 6,
      inputs: [
        createTransport(112),
        createTransport(113),
        createTransport(114),
        createTransport(115),
        createTransport(116),
        createTransport(117),
      ],
    },
    {
      id: 'CCKnobs',
      height: 2.125,
      width: 4.375,
      left: 9,
      bottom: 8.375,
      nRows: 2,
      nCols: 4,
      inputs: [
        createKnob(21),
        createKnob(22),
        createKnob(23),
        createKnob(24),
        createKnob(25),
        createKnob(26),
        createKnob(27),
        createKnob(28),
      ],
    },
    {
      id: 'Pads',
      height: 2.375,
      width: 5.25,
      left: 14,
      bottom: 8.25,
      nRows: 2,
      nCols: 4,
      inputs: [
        createPad(67),
        createPad(69),
        createPad(71),
        createPad(72),
        createPad(60),
        createPad(62),
        createPad(64),
        createPad(65),
      ],
    },
  ],
};
