import { DeviceDriver } from '../driver-types';
import {
  PadDriver,
  NoninteractiveInputDriver,
} from '../driver-types/input-drivers';

function createNoninteractivePad(
  width: number,
  height: number,
): NoninteractiveInputDriver {
  return {
    interactive: false,
    width,
    height,
    type: 'pad',
    shape: 'rect',
  };
}

function createPad(n: MidiNumber): PadDriver {
  return {
    interactive: true,
    status: 'controlchange',
    channel: 0,
    number: n,
    type: 'pad',
    width: 0.4,
    height: 0.25,
    shape: 'rect',
    response: 'gate',
    availableColors: [],
    availableFx: [],
  };
}

export const Device: DeviceDriver = {
  name: 'Impact GX61 MIDI1',
  type: 'normal',
  anonymous: false,
  width: 38,
  height: 7.75,
  controlSequence: [],
  style: {
    borderTopLeftRadius: '0.1em',
    borderTopRightRadius: '0.1em',
    borderBottomLeftRadius: '0.1em',
    borderBottomRightRadius: '0.1em',
  },
  keyboard: {
    defaultOctave: 1,
    nOctaves: 5,
    channel: 1,
    width: 33,
    height: 5.5,
    left: 4,
    bottom: 0.5,
    enabled: true,
  },
  inputGrids: [
    {
      id: 'Wheels',
      nRows: 1,
      nCols: 2,
      width: 2.125,
      height: 1.875,
      left: 1,
      bottom: 1,
      inputs: [
        {
          interactive: true,
          status: 'pitchbend',
          channel: 0,
          number: 0,
          type: 'wheel',
          width: 0.5,
          height: 2.125,
          shape: 'rect',
          response: 'continuous',
          handleWidth: 0.5,
          handleHeight: 0.5,
          horizontal: false,
          inverted: false,
          availableColors: [],
          availableFx: [],
        },
        {
          interactive: true,
          status: 'controlchange',
          channel: 0,
          number: 1,
          type: 'wheel',
          width: 0.5,
          height: 2.125,
          shape: 'rect',
          response: 'continuous',
          handleWidth: 0.5,
          handleHeight: 0.5,
          horizontal: false,
          inverted: false,
          availableColors: [],
          availableFx: [],
        },
      ],
    },
    {
      id: 'Internal Controls',
      nRows: 1,
      nCols: 4,
      width: 2.5,
      height: 0.25,
      left: 0.75,
      bottom: 3.7,
      inputs: [
        createNoninteractivePad(0.4, 0.25),
        createNoninteractivePad(0.4, 0.25),
        createNoninteractivePad(0.4, 0.25),
        createNoninteractivePad(0.4, 0.25),
      ],
    },
    {
      id: 'Playback',
      nRows: 2,
      nCols: 4,
      width: 2.5,
      height: 1.15,
      left: 0.75,
      bottom: 4.5,
      inputs: [
        createNoninteractivePad(0.4, 0.25),
        createPad(0),
        createPad(2),
        createPad(3),
        createPad(4),
        createPad(6),
        createPad(8),
        createPad(9),
      ],
    },
    {
      id: 'Knob',
      nRows: 1,
      nCols: 1,
      width: 0.875,
      height: 0.875,
      left: 1,
      bottom: 6.14,
      inputs: [
        {
          interactive: true,
          status: 'controlchange',
          channel: 0,
          number: 7,
          type: 'knob',
          width: 0.875,
          height: 0.875,
          knobType: 'absolute',
          shape: 'circle',
          response: 'continuous',
          availableColors: [],
          availableFx: [],
        },
      ],
    },
    {
      id: 'Setup',
      nRows: 1,
      nCols: 1,
      width: 0.25,
      height: 0.4,
      left: 2.5,
      bottom: 6.3,
      inputs: [createNoninteractivePad(0.4, 0.25)],
    },
  ],
};
